### PR TITLE
test: separate files for different test cases

### PR DESCRIPTION
**Pull request by sarayusreeyadavpadala**
Hey there! I am a beginner to Open Source and I am interested to contribute to Open Food Facts. Here, I've separated the test cases into different files and deleted the existing file. Let me know if any changes are needed. Looking forward to your suggestions.

### CODE REVIEW

**Comment by alexgarel** [comment]
@sarayusreeyadavpadala awesome to see your contributions.

I don't have time to review right now but I will maybe next week (if @aadarsh-ram does not have the time in-between).

**Comment by sarayusreeyadavpadala** [comment]
@alexgarel No problem, take your time.

**Review by sumit-158 — COMMENTED** [review]
@sarayusreeyadavpadala  Initial comments please use "make lint"

**Comment by sarayusreeyadavpadala** [comment]
> @sarayusreeyadavpadala Initial comment please use "make lint"

@sumit-158 Kindly elaborate further on what you have just said.

**Comment by aadarsh-ram** [comment]
Hi @sarayusreeyadavpadala! Thank you for the contributions. Currently, your PR is failing workflows, related to code quality and linting. Please use the `make lint` command at the root of the repo and commit again.

**Comment by sarayusreeyadavpadala** [comment]
> Hi @sarayusreeyadavpadala! Thank you for the contributions. Currently, your PR is failing workflows, related to code quality and linting. Please use the `make lint` command at the root of the repo and commit again. Someone will review your PR soon.

Thank you @aadarsh-ram
I shall attend to that task promptly within the day.

**Comment by sarayusreeyadavpadala** [comment]
@aadarsh-ram, @sumit-158 Could you please check my new commit once....

**Comment by sumit-158** [comment]
@sarayusreeyadavpadala  Seems like the Linting is not fixed yet :-) , make sure to use `make lint`. Lets us know if you face any issue :slightly_smiling_face: Please refer this [link](https://github.com/openfoodfacts/facets-knowledge-panels/blob/main/docs/how-to-guides/Testing.md)

**Comment by sarayusreeyadavpadala** [comment]
> @sarayusreeyadavpadala Seems like the Linting is not fixed yet :-) , make sure to use `make lint`. Lets us know if you face any issue 🙂 Please refer this [link](https://github.com/openfoodfacts/facets-knowledge-panels/blob/main/docs/how-to-guides/Testing.md)

Thank you @sumit-158

**Comment by sarayusreeyadavpadala** [comment]
> @sarayusreeyadavpadala Seems like the Linting is not fixed yet :-) , make sure to use `make lint`. Lets us know if you face any issue 🙂 Please refer this [link](https://github.com/openfoodfacts/facets-knowledge-panels/blob/main/docs/how-to-guides/Testing.md)

@sumit-158 when I run "make lint" command, it shows-
docker-compose run --rm --no-deps facets-api isort .
process_begin: CreateProcess(NULL, docker-compose run --rm --no-deps facets-api isort ., ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:20: lint] Error 2

**Comment by sumit-158** [comment]
@stephanegigandet Can you use Slack for further discussion? [Join us](https://openfoodfacts.slack.com/) in the channel  `#Knowledge-panel`

**Comment by sarayusreeyadavpadala** [comment]
I have sorted the imports using "isort" this time. And also used "black".

**Comment by sarayusreeyadavpadala** [comment]
Could anyone approve the workflows.

**Review by sumit-158 — COMMENTED** [review]
Hi @sarayusreeyadavpadala  good work, I have made a push for the lint issue, and now it is resolved but tests are failing, please look into it :-)
tip: use `docker-compose run --rm --no-deps facets-api pytest -vv .`  to see the total output of tests and why and where it is failing

**Comment by sarayusreeyadavpadala** [comment]
> Hi @sarayusreeyadavpadala good work, I have made a push for the lint issue, and now it is resolved but tests are failing, please look into it :-) tip: use `docker-compose run --rm --no-deps facets-api pytest -vv .` to see the total output of tests and why and where it is failing

Thank you @sumit-158

**Pull request closed without merging**
