### PR TITLE
docs: Update README.md

### PR DESCRIPTION
**Pull request by utkarsh006**
- Enhanced README file for this Repo for better readability of users.
- Added Contributors section and about the details of the repo.
- Formatted some lines of text.

## Output Screenshots

Screenshot (195)
Screenshot (196)

### CODE REVIEW

**Comment by sumit-158** [comment]
Hi @utkarsh006 Great work 👍🏼

**Review by sumit-158 — COMMENTED** [review]
It would be better if you could move the "About Repo" section below the "How do I get started?" section :)

**Comment by utkarsh006** [comment]
> It would be better if you could move the "About Repo" section below the "How do I get started?" section :)

Thanks so much for reviewing my PR. Yes, I will do the required changes.

**Comment by utkarsh006** [comment]
@sumit-158 I have done the changes. Kindly review and merge :)

**Review by sumit-158 — APPROVED** [review]
LGTM!

**Comment by utkarsh006** [comment]
@sumit-158 Thanks Buddy ! Do Merge it ⭐

**Review by teolemon — APPROVED** [review]

**Pull request merged**
